import re
import json
import hashlib
import logging
import asyncio
from telegram import (
    Update,
    BotCommand,
    KeyboardButton,
    ReplyKeyboardMarkup,
    InlineKeyboardButton,
    InlineKeyboardMarkup
)
from telegram.ext import ContextTypes, Application
from ai_core import clear_context, process_chat_message, extract_followups_from_text
from tools.file_intel import process_uploaded_document

logger = logging.getLogger(__name__)

# Prompt cache to keep Telegram callback_data strictly <= 64 bytes
PROMPT_CACHE: dict[str, str] = {}


def cache_prompt(prompt_text: str) -> str:
    """Cache prompt text and return short key for Telegram callback_data (<= 64 bytes limit)."""
    h = hashlib.md5(prompt_text.encode("utf-8")).hexdigest()[:12]
    key = f"p:{h}"
    PROMPT_CACHE[key] = prompt_text
    return key


def get_cached_prompt(key: str) -> str:
    """Retrieve original prompt text by short key."""
    return PROMPT_CACHE.get(key, key)


def extract_primary_subject(user_input: str, response_text: str = "") -> dict:
    """Extract primary stock ticker or macro topic from input/response as a heuristic fallback."""
    text = (user_input + " " + (response_text[:300] if response_text else "")).strip()

    # 1. Match Taiwan stock codes (e.g. 2330, 2330.TW, 3293.TWO)
    tw_match = re.search(r"\b(\d{4,6}(?:\.TW|\.TWO)?)\b", text, re.IGNORECASE)
    if tw_match:
        code = tw_match.group(1).upper()
        return {"type": "stock", "ticker": code}

    # 2. Match US tickers (2-5 uppercase letters)
    us_match = re.search(r"\b([A-Z]{2,5})\b", user_input)
    if us_match and us_match.group(1) not in (
        "AI", "DCF", "PE", "EPS", "WACC", "FCF", "SEPA", "VCP", "SPY", "USD", "TOC", "API"
    ):
        return {"type": "stock", "ticker": us_match.group(1)}

    # 3. Match known Chinese company names
    company_map = {
        "台積電": "2330.TW", "聯發科": "2454.TW", "鴻海": "2317.TW", "長榮": "2603.TW",
        "鈊象": "3293.TWO", "元太": "8069.TWO", "特斯拉": "TSLA", "輝達": "NVDA", "蘋果": "AAPL",
        "微軟": "MSFT", "谷歌": "GOOGL", "亞馬遜": "AMZN", "博通": "AVGO", "超微": "AMD"
    }
    for name, sym in company_map.items():
        if name in text:
            return {"type": "stock", "ticker": sym, "name": name}

    # 4. Match macro keywords
    macro_keywords = ["降息", "升息", "通膨", "聯準會", "關稅", "非農", "地緣政治", "油價", "美債", "日圓", "AI產業"]
    for kw in macro_keywords:
        if kw in text:
            return {"type": "macro", "topic": kw}

    return {"type": "general"}


def generate_followup_keyboard(
    user_input: str,
    response_text: str = "",
    dynamic_followups: list[str] = None
) -> InlineKeyboardMarkup:
    """
    Dynamically generate contextual follow-up prompt buttons.
    Prioritizes real, bespoke prompts generated by the LLM based on conversation context.
    """
    buttons = []

    # 1. First priority: Contextual follow-up suggestions generated by LLM
    if dynamic_followups and len(dynamic_followups) > 0:
        for prompt in dynamic_followups[:4]:
            prompt_str = prompt.strip()
            if prompt_str:
                label = prompt_str if len(prompt_str) <= 30 else prompt_str[:28] + "..."
                key = cache_prompt(prompt_str)
                buttons.append([InlineKeyboardButton(label, callback_data=key)])
        if buttons:
            return InlineKeyboardMarkup(buttons)

    # 2. Fallback heuristic buttons if LLM omitted dynamic tags
    subj = extract_primary_subject(user_input, response_text)
    if subj["type"] == "stock":
        sym = subj["ticker"]
        is_tw = ".TW" in sym or ".TWO" in sym or sym.isdigit()
        clean_code = sym.replace(".TW", "").replace(".TWO", "")

        if is_tw:
            buttons.append([
                InlineKeyboardButton(f"🏢 查 {clean_code} 三大法人籌碼", callback_data=cache_prompt(f"/chip {sym}")),
                InlineKeyboardButton(f"💰 計算 {clean_code} DCF 合理價", callback_data=cache_prompt(f"/val {sym}"))
            ])
            buttons.append([
                InlineKeyboardButton(f"📐 檢驗 {clean_code} SEPA 趨勢", callback_data=cache_prompt(f"/sepa {sym}")),
                InlineKeyboardButton(f"🏛️ 14 大師圓桌辯論", callback_data=cache_prompt(f"/ai2 {sym}"))
            ])
        else:
            buttons.append([
                InlineKeyboardButton(f"💰 計算 {sym} DCF 內在價值", callback_data=cache_prompt(f"/val {sym}")),
                InlineKeyboardButton(f"📐 檢驗 {sym} SEPA 趨勢", callback_data=cache_prompt(f"/sepa {sym}"))
            ])
            buttons.append([
                InlineKeyboardButton(f"📊 {sym} 多因子風險歸因", callback_data=cache_prompt(f"/ff {sym}")),
                InlineKeyboardButton(f"🏛️ 14 大師圓桌辯論", callback_data=cache_prompt(f"/ai2 {sym}"))
            ])

    elif subj["type"] == "macro":
        topic = subj["topic"]
        buttons.append([
            InlineKeyboardButton(f"⛓️ 分析「{topic}」金融傳導鏈", callback_data=cache_prompt(f"/chain {topic}")),
            InlineKeyboardButton("🔥 查看全球重大快訊", callback_data=cache_prompt("/hot"))
        ])
        buttons.append([
            InlineKeyboardButton("🏢 查台積電 2330 法人籌碼", callback_data=cache_prompt("/chip 2330.TW")),
            InlineKeyboardButton("📊 輝達 NVDA 多因子模型", callback_data=cache_prompt("/ff NVDA"))
        ])

    else:
        buttons.append([
            InlineKeyboardButton("🔥 查看即時重大快訊", callback_data=cache_prompt("/hot")),
            InlineKeyboardButton("🏢 台積電 2330 法人籌碼", callback_data=cache_prompt("/chip 2330.TW"))
        ])
        buttons.append([
            InlineKeyboardButton("📊 輝達 NVDA 多因子歸因", callback_data=cache_prompt("/ff NVDA")),
            InlineKeyboardButton("💰 特斯拉 TSLA DCF估值", callback_data=cache_prompt("/val TSLA"))
        ])

    return InlineKeyboardMarkup(buttons)


async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    # Reset conversation context
    thread_id = str(update.effective_chat.id)
    await clear_context(thread_id)

    help_message = (
        "🎉 **歡迎使用 DAVID888 股票資訊與 AI 投資分析機器人！**\n\n"
        "*(您的對話記憶已重置，現在是一個全新的開始)*\n\n"
        "💬 **自然語言智能對話（直接傳送文字即可）**：\n"
        "機器人已整合量化模型、2MD 全網情報、即時股價、技術指標與新聞。您可以像與研究員對話一樣直接詢問：\n"
        "  • 📐 *「TSLA 目前符合 Minervini SEPA 突破與 Stage 2 嗎？」*\n"
        "  • 💰 *「幫我計算 AAPL 的五年 DCF 內在價值與合理價」*\n"
        "  • 🏢 *「台積電 2330 最近外資與投信連買幾天？三大法人買賣超如何？」*\n"
        "  • 📊 *「分析 NVDA 的 Fama-French 多因子模型與超額報酬 Alpha 歸因」*\n"
        "  • 🗓️ *「NVDA 下週財報預期與過去四季驚喜度如何？」*\n"
        "  • 🏛️ *「巴菲特和段永平最近有買進或加減持哪檔股票？(13F持倉)」*\n"
        "  • 🕵️ *「查詢 TSLA 最近的高階經理人內部人買賣 (Form 4)」*\n"
        "  • 🚀 *「分析 GME 的做空比率與軋空 (Short Squeeze) 風險」*\n"
        "  • 📰 *「台積電 2330.TW 最近有什麼重大新聞與基本面評估」*\n\n"
        "📎 **智慧文件與對帳單解析（Google Magika 驅動）**：\n"
        "直接在聊天室發送 **PDF 財報/研報**、**CSV/Excel 投資對帳單與數據表** 或 **TXT 文件**（可附帶文字備註）：\n"
        "  • 🛡️ 透過 **Google Magika** 進行 100% 本地深層格式識別與安全檢測，阻截可執行檔偽裝。\n"
        "  • 🤖 AI 專家將為您自動萃取報表數據，深度解析財務體質、營運亮點與資產配置建議！\n\n"
        "📌 **專屬量化與委員會指令速查**：\n"
        "• `/chain 事件或主題` - ⛓️ 金融邏輯傳導鏈分析與因果流程圖 (範例：`/chain 聯準會降息`)\n"
        "• `/hot [來源]` - 🔥 財聯社/華爾街見聞/雪球即時快訊 (範例：`/hot` 或 `/hot wallstreetcn`)\n"
        "• `/chip 股票代碼` - 🏢 台股三大法人買賣超、連買連賣與外資持股 (範例：`/chip 2330.TW`)\n"
        "• `/ff 股票代碼` - 📊 Fama-French 多因子風險歸因與 Alpha (範例：`/ff NVDA`)\n"
        "• `/sepa 股票代碼` - 📐 Minervini SEPA 8 項趨勢模板與 VCP 篩選 (範例：`/sepa TSLA`)\n"
        "• `/val 股票代碼` - 💰 五年 DCF 內在價值與 WACC 敏感度 (範例：`/val AAPL`)\n"
        "• `/earn 股票代碼` - 🗓️ 財報日期、共識預估與四季驚喜紀錄 (範例：`/earn NVDA`)\n"
        "• `/corr 股票1,股票2,...` - 🔗 90 日相關係數與 S&P 500 Beta (範例：`/corr TSLA,NVDA,AAPL`)\n"
        "• `/ai2 股票代碼` - 🏛️ 14 位投資大師 AI 對沖基金委員會與圓桌辯論 (範例：`/ai2 NVDA`)\n"
        "• `/s 股票代碼` - 📈 查詢即時股價與 日/週/月 K 線圖 (範例：`/s 2330.TW`)\n"
        "• `/p 股票代碼` - 🔮 Prophet 時間序列預測未來 5 天股價區間 (範例：`/p META`)\n"
        "• `/n 股票代碼或公司名` - 📰 智慧檢索台美股即時財經新聞 (範例：`/n 2330`、`/n 台積電`、`/n TSLA`、`/n 特斯拉`)\n"
        "• `/new` 或 `/clear` - 🧹 清空對話記憶開啟全新對話 (3 天無互動亦會自動重置)\n"
        "• `/h` - 🛠️ 顯示其他外部量化預測工具連結\n"
        "• `/start` 或 `/help` - 🔄 重置記憶並顯示此說明選單"
    )
    keyboard = ReplyKeyboardMarkup(
        keyboard=[
            [KeyboardButton("/chain 聯準會降息"), KeyboardButton("/hot")],
            [KeyboardButton("/chip 2330.TW"), KeyboardButton("/ff NVDA")],
            [KeyboardButton("/sepa TSLA"), KeyboardButton("/val AAPL")],
            [KeyboardButton("/earn NVDA"), KeyboardButton("/s 2330.TW")],
            [KeyboardButton("/new"), KeyboardButton("/ai2 NVDA")]
        ],
        resize_keyboard=True
    )
    await update.message.reply_text(help_message, reply_markup=keyboard, parse_mode="Markdown")


async def new_conversation_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """Handler for /new and /clear command to reset conversation memory."""
    thread_id = str(update.effective_chat.id)
    await clear_context(thread_id)
    await update.message.reply_text(
        "🧹 **對話記憶已清空，為您開啟全新對話！**\n\n您可以隨時開始輸入股票代碼、量化問題或財經話題。",
        parse_mode="Markdown"
    )


async def tools_help(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message = (
        "🛠 **其他股票與量化工具**\n\n"
        "📊 台股預測 (LSTM)：[點擊使用](https://huggingface.co/spaces/tbdavid2019/twStock-predict)\n"
        "📈 美股台股潛力股預測 (LSTM)：[點擊使用](https://huggingface.co/spaces/tbdavid2019/twStock-Underdogs)\n"
        "🔮 美股台股預測 (Prophet)：[點擊使用](https://huggingface.co/spaces/tbdavid2019/Stock-Predict-Prophet)\n"
        "🏛️ AI 對沖基金 (14位投資大師與圓桌辯論)：[點擊使用](https://huggingface.co/spaces/tbdavid2019/ai-hedge-fund)"
    )
    await update.message.reply_text(message, parse_mode="Markdown")


def split_telegram_text(text: str, limit: int = 3900) -> list[str]:
    """Split long output into chunks strictly within Telegram 4096 char limit."""
    if len(text) <= limit:
        return [text]
    chunks = []
    remaining = text
    while len(remaining) > limit:
        split_at = remaining.rfind("\n\n", 0, limit)
        if split_at < limit // 2:
            split_at = remaining.rfind("\n", 0, limit)
        if split_at < limit // 2:
            split_at = limit
        chunks.append(remaining[:split_at].rstrip())
        remaining = remaining[split_at:].lstrip()
    if remaining:
        chunks.append(remaining)
    return chunks


async def safe_reply_chunks(message, text: str, reply_markup=None):
    """Safely reply with text chunks, attaching reply_markup to the final message."""
    chunks = split_telegram_text(text)
    for i, chunk in enumerate(chunks):
        is_last = (i == len(chunks) - 1)
        markup = reply_markup if is_last else None
        try:
            await message.reply_text(
                chunk,
                reply_markup=markup,
                parse_mode="Markdown",
                disable_web_page_preview=True
            )
        except Exception:
            await message.reply_text(
                chunk,
                reply_markup=markup,
                disable_web_page_preview=True
            )


async def default_message_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle regular text messages by passing them to the Main LLM Agent.
    Generates dynamic, context-aware follow-up prompt buttons tailored to the discussion.
    """
    user_input = update.message.text
    if not user_input:
        return

    # Notify user that bot is typing and send temporary status message
    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")
    processing_msg = await update.message.reply_text("⏳ 思考與處理中，請稍候...")

    try:
        # Process message via Main Agent with conversation memory
        thread_id = str(update.effective_chat.id)
        raw_response = await process_chat_message(user_input, thread_id=thread_id)

        # Delete the temporary processing message
        try:
            await processing_msg.delete()
        except Exception:
            pass

        if not raw_response or not str(raw_response).strip():
            raw_response = "⚠️ 系統分析完成，但未生成文字回覆，請嘗試重新提問或使用專屬指令（如 /val、/sepa、/chain）。"

        clean_response, followups = extract_followups_from_text(raw_response)
        followup_markup = generate_followup_keyboard(user_input, clean_response, dynamic_followups=followups)

        await safe_reply_chunks(update.message, clean_response, reply_markup=followup_markup)
    except Exception as e:
        logger.error(f"Default message handler error: {e}")
        try:
            await processing_msg.delete()
        except Exception:
            pass
        await update.message.reply_text(f"❌ 處理訊息時發生錯誤：{str(e)}")


async def document_message_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle uploaded files (PDF, CSV, Excel, TXT, JSON) via Google Magika & LLM Agent.
    
    1. Downloads file stream from Telegram (<= 20MB limit).
    2. Runs Google Magika deep learning identification (100% local CPU ONNX runtime).
    3. Blocks malicious executables, binaries, or dangerous scripts.
    4. Safely parses content (PDF pages, CSV/Excel tables, text feeds).
    5. Injects structured extraction & user caption into LLM Agent for comprehensive financial analysis.
    """
    message = update.message
    if not message or not message.document:
        return

    doc = message.document
    file_name = doc.file_name or "uploaded_file"
    file_size = doc.file_size or 0
    user_caption = (message.caption or "").strip()

    # Telegram Bot API enforces a 20MB limit for get_file()
    if file_size > 20 * 1024 * 1024:
        await message.reply_text(
            f"⚠️ **檔案過大（{file_size / (1024*1024):.1f} MB）**\n\n"
            f"Telegram 官方限制機器人單次下載上限為 20MB，請壓縮或上傳小於 20MB 的檔案。"
        )
        return

    await context.bot.send_chat_action(chat_id=update.effective_chat.id, action="typing")
    status_msg = await message.reply_text(
        f"📥 **接收檔案中**：`{file_name}` ({file_size / 1024:.1f} KB)\n"
        f"🔍 調用 Google Magika 進行本地深度格式識別與安全檢測..."
    )

    try:
        # Download file bytes from Telegram
        tg_file = await doc.get_file()
        file_bytes = await tg_file.download_as_bytearray()

        # Run CPU-bound Magika identification and document parsing in thread executor
        loop = asyncio.get_running_loop()
        res = await loop.run_in_executor(
            None,
            process_uploaded_document,
            bytes(file_bytes),
            file_name
        )

        # 1. Security check
        if not res.get("is_safe", False):
            try:
                await status_msg.delete()
            except Exception:
                pass
            await message.reply_text(res.get("error", "檔案安全檢驗未通過。"))
            return

        # 2. Parsing check
        if not res.get("success", False):
            try:
                await status_msg.delete()
            except Exception:
                pass
            await message.reply_text(f"❌ **檔案解析未完成**\n\n{res.get('error', '無法擷取有效文字或數據內容')}")
            return

        # 3. Extract metadata and prepare LLM prompt
        detection = res.get("detection", {})
        label = detection.get("label", "unknown")
        score = detection.get("score", 1.0)
        doc_type = res.get("doc_type", label)
        extracted_text = res.get("extracted_text", "")
        file_size_kb = file_size / 1024

        try:
            await status_msg.edit_text(
                f"✅ **Google Magika 辨識完成**：`{doc_type}`（識別標籤 `{label}`，置信度 {score:.1%}）\n"
                f"🤖 AI 投研專家正在為您進行深度剖析與洞察，請稍候..."
            )
        except Exception:
            pass

        full_prompt = (
            f"【使用者上傳財務/投資檔案】\n"
            f"- 檔案名稱：`{file_name}`\n"
            f"- 檔案格式：{doc_type}（Google Magika 辨識標籤：`{label}`，置信度：{score:.1%}）\n"
            f"- 檔案大小：{file_size_kb:.1f} KB\n\n"
            f"【使用者指定分析需求】：\n"
            f"{user_caption if user_caption else '（使用者未輸入文字備註。請主動對本文件進行專業投資與財務分析，整理關鍵財務指標、營運亮點、數據洞察與風險評估）'}\n\n"
            f"【文件擷取內容】：\n"
            f"{extracted_text}\n"
        )

        thread_id = str(update.effective_chat.id)
        raw_response = await process_chat_message(full_prompt, thread_id=thread_id)

        try:
            await status_msg.delete()
        except Exception:
            pass

        if not raw_response or not str(raw_response).strip():
            raw_response = "⚠️ 系統分析完成，但未生成文字回覆，請嘗試重新提問。"

        clean_response, followups = extract_followups_from_text(raw_response)
        followup_markup = generate_followup_keyboard(user_caption or file_name, clean_response, dynamic_followups=followups)

        # Prepend file inspection badge at top of clean_response
        file_badge = (
            f"📂 **【Google Magika 檔案解析報告】**\n"
            f"• 檔案：`{file_name}` ({file_size_kb:.1f} KB)\n"
            f"• 格式：`{doc_type}` (信心度: `{score:.1%}`)\n\n"
        )
        final_reply = file_badge + clean_response

        await safe_reply_chunks(message, final_reply, reply_markup=followup_markup)

    except Exception as e:
        logger.error(f"Document message handler error: {e}", exc_info=True)
        try:
            await status_msg.delete()
        except Exception:
            pass
        await message.reply_text(f"❌ 處理上傳檔案時發生錯誤：{str(e)}")


async def callback_prompt_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """
    Handle clicks on dynamic follow-up prompt buttons.
    Dispatches slash commands or triggers an organic follow-up analysis with LLM.
    """
    query = update.callback_query
    await query.answer()

    data = query.data or ""
    prompt_text = ""

    # 1. Try memory cache first
    if data in PROMPT_CACHE:
        prompt_text = PROMPT_CACHE[data]
    elif data.startswith("prompt:"):
        prompt_text = data[len("prompt:"):].strip()

    # 2. Resilient Fallback: Retrieve exact button text from message reply_markup if cache missed (e.g. server restarted)
    if not prompt_text and query.message and query.message.reply_markup:
        for row in query.message.reply_markup.inline_keyboard:
            for btn in row:
                if btn.callback_data == data:
                    prompt_text = btn.text.strip()
                    break
            if prompt_text:
                break

    # 3. Final fallback
    if not prompt_text:
        prompt_text = data.replace("p:", "").strip()

    if not prompt_text:
        return

    # Dispatch commands if prompt is a direct slash command
    if prompt_text.startswith("/"):
        parts = prompt_text.split()
        cmd = parts[0].lower()
        args = parts[1:]
        context.args = args

        if cmd == "/chip":
            from handlers.stock_cmds import institutional_chip_analysis
            await institutional_chip_analysis(update, context)
            return
        elif cmd == "/val":
            from handlers.stock_cmds import valuation_analysis
            await valuation_analysis(update, context)
            return
        elif cmd == "/sepa":
            from handlers.stock_cmds import sepa_analysis
            await sepa_analysis(update, context)
            return
        elif cmd == "/earn":
            from handlers.stock_cmds import earnings_briefing
            await earnings_briefing(update, context)
            return
        elif cmd == "/corr":
            from handlers.stock_cmds import correlation_analysis
            await correlation_analysis(update, context)
            return
        elif cmd == "/ff":
            from handlers.stock_cmds import fama_french_analysis
            await fama_french_analysis(update, context)
            return
        elif cmd == "/ai2":
            from handlers.ai_cmds import ai2_analysis
            await ai2_analysis(update, context)
            return
        elif cmd == "/chain":
            from handlers.stock_cmds import chain_analysis
            await chain_analysis(update, context)
            return
        elif cmd == "/hot":
            from handlers.stock_cmds import hot_news_query
            await hot_news_query(update, context)
            return
        elif cmd == "/n" or cmd == "/ny":
            from handlers.stock_cmds import stock_news
            await stock_news(update, context)
            return

    # Natural language prompt: feed back to LLM agent with conversation context
    thread_id = str(update.effective_chat.id)
    processing_msg = await query.message.reply_text(
        f"💬 *已選擇續問：* `{prompt_text}`\n⏳ 深度分析中，請稍候...",
        parse_mode="Markdown"
    )
    try:
        raw_response = await process_chat_message(prompt_text, thread_id=thread_id)
        try:
            await processing_msg.delete()
        except Exception:
            pass

        clean_response, followups = extract_followups_from_text(raw_response)
        followup_markup = generate_followup_keyboard(prompt_text, clean_response, dynamic_followups=followups)

        try:
            await query.message.reply_text(clean_response, reply_markup=followup_markup, parse_mode="Markdown")
        except Exception:
            await query.message.reply_text(clean_response, reply_markup=followup_markup)
    except Exception as e:
        logger.error(f"Callback prompt handler error: {e}")
        try:
            await processing_msg.delete()
        except Exception:
            pass
        await query.message.reply_text(f"❌ 處理續問時發生錯誤：{str(e)}")


async def reset_commands(application: Application):
    commands = [
        BotCommand("start", "啟動機器人與重置對話記憶"),
        BotCommand("new", "清空對話記憶開啟全新對話"),
        BotCommand("clear", "清空對話記憶開啟全新對話"),
        BotCommand("chain", "金融邏輯傳導鏈分析 (因果流程圖)"),
        BotCommand("hot", "即時重大財經快訊 (財聯社/華爾街見聞)"),
        BotCommand("chip", "台股三大法人買賣超與連買連賣籌碼分析"),
        BotCommand("ff", "Fama-French 多因子風險歸因與 Alpha"),
        BotCommand("ai2", "14位投資大師圓桌辯論 (AI對沖基金)"),
        BotCommand("s", "查詢即時股價和日/週/月 K 線圖"),
        BotCommand("p", "Prophet 模型預測未來 5 天股價"),
        BotCommand("sepa", "Minervini SEPA 趨勢模板與 VCP 分析"),
        BotCommand("val", "五年 DCF 內在價值與 WACC 敏感度"),
        BotCommand("earn", "財報日期與四季盈餘驚喜簡報"),
        BotCommand("corr", "多股相關係數與 S&P 500 Beta"),
        BotCommand("n", "智慧檢索台美股即時財經新聞 (支援代碼與中文名)"),
        BotCommand("ny", "智慧檢索台股即時財經新聞 (別名)"),
        BotCommand("h", "顯示量化預測工具連結"),
        BotCommand("help", "顯示完整功能說明與指令表")
    ]
    await application.bot.set_my_commands(commands)
